import type { Metadata } from 'next'
import './globals.css'
import AppProvider from '@/app/AppProvider'

export const metadata: Metadata = {
  title: '爱农宝运营后台',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh">
      <body className="flex h-screen">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
